theme: jekyll-theme-minimal
title: OctaDist
description: A tool for calculating distortion parameters in coordination complexes.
logo: images/molecule.png
show_downloads: false
google_analytics: UA-135002233-1

plugin:
  - jekyll-mentions
