theme: jekyll-theme-minimal
title: OctaDist
description: Structural distortion analysis of octahedral structure
logo: https://github.com/OctaDist/OctaDist.github.io/blob/master/molecule.png
show_downloads: true
